# Generated by Django 5.2.12 on 2026-04-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.PositiveIntegerField(unique=True)),
                ('division_id', models.PositiveIntegerField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('bn_name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
            ],
            options={
                'ordering': ['source_id'],
            },
        ),
    ]
