# Generated by Django 5.2.12 on 2026-04-08 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_temp_2pm_7d', models.FloatField()),
                ('avg_pm25_7d', models.FloatField()),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('district', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='travel_score', to='app_core.district')),
            ],
            options={
                'ordering': ['avg_temp_2pm_7d', 'avg_pm25_7d', 'district__source_id'],
            },
        ),
    ]
