# Generated by Django 5.2.12 on 2026-04-09 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0002_districtscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('temp_2pm', models.FloatField()),
                ('pm25_2pm', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='app_core.district')),
            ],
            options={
                'ordering': ['forecast_date'],
                'unique_together': {('district', 'forecast_date')},
            },
        ),
    ]
