# Generated by Django 5.2.12 on 2026-04-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0003_districtforecast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtscore',
            name='avg_pm25_7d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='districtscore',
            name='avg_temp_2pm_7d',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
